Repository TheSGJ/nextjs-toploader, pull requests merged in 2025-03, with the labels that each got.

#117 bump: update actions deprecated deps
  .github/workflows/build-deploy.yml
  .github/workflows/continuous-integration.yml
  src/index.tsx
Labels: dependencies

#114 feat: add useTopLoader hook for managing NextTopLoader
  README.md
  src/hooks/useTopLoader.tsx
  src/index.tsx
Labels: enhancement

#124 fix: for custom targets and update year in LICENSE to current
  CHANGELOG.md
  LICENSE
  deno.json
  package.json
  src/index.tsx
Labels: bug, documentation
